language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

install:
  - pip install -r requirements_dev.txt --use-mirrors
  - python setup.py install

script: py.test testing/

branches:
  only:
    - master
